### ISSUE TITLE
Kafka Connector error

### ISSUE THREAD

**Issue by heitorsampaio** [ksmin23/aws-msk-debezium-cdc-data-pipeline#1]
Hey,

I was following up your tutorial, but when i try to create the Kafka Connector i got this error.

`12:19:15 PM | CREATE_FAILED        | AWS::KafkaCon
nect::Connector | KafkaCfnConnector
Resource handler returned message: "Error occurred
during operation 'Couldn't create AWS::KafkaConnec
t::Connector due to create failure'." (RequestToke
n: b2715f84-98a4-ca77-c41a-f9ad3d566519, HandlerEr
rorCode: GeneralServiceException)`

**Comment by heitorsampaio** [comment]
UPDATE:

I found this exception.

`[Worker-01927674c85d39ac7] [2023-11-10 14:21:38,381] ERROR ClassNotFoundException exception occurred: com.github.jcustenborder.kafka.config.aw.SecretsManagerConfigProvider (org.apache.kafka.connect.runtime.distributed.DistributedConfig:551)`

**Comment by ksmin23** [comment]
It seems that you did not create a custom plugin package and upload it to S3.
I think you need to make sure you complete the [prerequisites](https://github.com/ksmin23/aws-msk-debezium-cdc-data-pipeline#prerequisites)

**Comment by heitorsampaio** [comment]
I've cheked the zip file, I've followed the prerequisites, can you upload your zip file, just to make sure that I've not make any mistake.

**Comment by heitorsampaio** [comment]
I found the error, was my mistake, my worker configurator was miss typing `config.providers.secretManager.class=com.github.jcustenborder.kafka.config.aw.SecretsManagerConfigProvider`. Thanks for you help anyway.
